Models/Projects/BurndownModel.cs
using CodeBuggy.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Security.Claims;

namespace CodeBuggy.Models.Projects;

public class BurndownModel
{
    private static readonly ILogger<BurndownModel> _logger = LoggerFactory.Create(builder =>
    {
        builder.AddConsole();
    }).CreateLogger<BurndownModel>();

    public void StoreBurndownData(AppDbContext context, int projectId)
    {
        try
        {
            var project = context.Projects.FirstOrDefault(p => p.Id == projectId);

            if (project == null)
            {
                _logger.LogError("Project not found.");
                return;
            }

            var tickets = context.Tickets
                .Where(t => project.TicketsId.Contains(t.Id))
                .ToList();

            var currentDate = DateTime.UtcNow.Date;

            var ticketGroups = tickets
                .GroupBy(t => new { t.Status, t.Priority })
                .Select(group => new
                {
                    Status = group.Key.Status,
                    Priority = group.Key.Priority,
                    Count = group.Count()
                });

            // Check if theres already data today
            var existingData = context.BurndownData
                .Where(d => d.ProjectId == projectId && d.DailyCounts.Any(dc => dc.Date == currentDate))
                .FirstOrDefault();

            if (existingData != null)
            {
                existingData.DailyCounts.First().ToDoCount = ticketGroups.Where(g => g.Status == TicketStatus.ToDo).Sum(g => g.Count);
                existingData.DailyCounts.First().InProgressCount = ticketGroups.Where(g => g.Status == TicketStatus.InProgress).Sum(g => g.Count);
                existingData.DailyCounts.First().ReviewCount = ticketGroups.Where(g => g.Status == TicketStatus.Review).Sum(g => g.Count);
                existingData.DailyCounts.First().DoneCount = ticketGroups.Where(g => g.Status == TicketStatus.Done).Sum(g => g.Count);
                existingData.DailyCounts.First().NonePriorityCount = ticketGroups.Where(g => g.Priority == TicketPriority.None).Sum(g => g.Count);
                existingData.DailyCounts.First().LowPriorityCount = ticketGroups.Where(g => g.Priority == TicketPriority.Low).Sum(g => g.Count);
                existingData.DailyCounts.First().MediumPriorityCount = ticketGroups.Where(g => g.Priority == TicketPriority.Medium).Sum(g => g.Count);
                existingData.DailyCounts.First().HighPriorityCount = ticketGroups.Where(g => g.Priority == TicketPriority.High).Sum(g => g.Count);
                existingData.DailyCounts.First().UrgentPriorityCount = ticketGroups.Where(g => g.Priority == TicketPriority.Urgent).Sum(g => g.Count);

                context.BurndownData.Update(existingData);
            }
            else
            {
                var newData = new BurndownData
                {
                    ProjectId = projectId,
                    DailyCounts = new List<DailyTicketCounts>
                    {
                        new DailyTicketCounts
                        {
                            Date = currentDate,
                            ToDoCount = ticketGroups.Where(g => g.Status == TicketStatus.ToDo).Sum(g => g.Count),
                            InProgressCount = ticketGroups.Where(g => g.Status == TicketStatus.InProgress).Sum(g => g.Count),
                            ReviewCount = ticketGroups.Where(g => g.Status == TicketStatus.Review).Sum(g => g.Count),
                            DoneCount = ticketGroups.Where(g => g.Status == TicketStatus.Done).Sum(g => g.Count),
                            NonePriorityCount = ticketGroups.Where(g => g.Priority == TicketPriority.None).Sum(g => g.Count),
                            LowPriorityCount = ticketGroups.Where(g => g.Priority == TicketPriority.Low).Sum(g => g.Count),
                            MediumPriorityCount = ticketGroups.Where(g => g.Priority == TicketPriority.Medium).Sum(g => g.Count),
                            HighPriorityCount = ticketGroups.Where(g => g.Priority == TicketPriority.High).Sum(g => g.Count),
                            UrgentPriorityCount = ticketGroups.Where(g => g.Priority == TicketPriority.Urgent).Sum(g => g.Count),
                        }
                    }
                };

                context.BurndownData.Add(newData);
            }

            context.SaveChanges();
        }
        catch (Exception ex)
        {
            _logger.LogError("Error storing Burndown data: " + ex);
        }
    }

    public List<DailyTicketCounts> GetBurndownData(AppDbContext context, int projectId)
    {
        try
        {
            var burndownData = context.BurndownData
                .Where(d => d.ProjectId == projectId)
                .Include(d => d.DailyCounts)
                .ToList();

            if (burndownData.Any())
            {
                // Concatenate all DailyCounts from different BurndownData entities
                var allDailyCounts = burndownData.SelectMany(d => d.DailyCounts).ToList();
                _logger.LogInformation("Burndown Data: " + JsonConvert.SerializeObject(allDailyCounts));

                return allDailyCounts;
            }

            return new List<DailyTicketCounts>();
        }
        catch (Exception ex)
        {
            _logger.LogError("Error retrieving Burndown data: " + ex);
            return null;
        }
    }

    public bool ValidUserClaim(AppDbContext context, UserManager<AppUser> userManager, ClaimsPrincipal user, int projectId)
    {
        var userId = userManager?.GetUserId(user);
        if (userId == null)
        {
            return false;
        }

        var foundUserClaim = context.UserClaims.FirstOrDefault(p => p.ClaimValue == projectId.ToString() && p.ClaimType == "ProjectAccess" && p.UserId == userId);
        if (foundUserClaim == null)
        {
            return false;
        }

        return true;
    }
}

Controllers/BurndownController.cs
using Microsoft.AspNetCore.Mvc;
using CodeBuggy.Data;
using CodeBuggy.Models.Projects;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;

public class BurndownController : Controller
{
    private readonly ILogger<BurndownController> _logger;
    private readonly BurndownModel _burndownModel;
    private readonly AppDbContext _context;
    private readonly UserManager<AppUser> _userManager;

    // Private field to store projectId
    private int _projectId;

    public BurndownController(ILogger<BurndownController> logger, AppDbContext context, UserManager<AppUser> userManager)
    {
        _logger = logger;
        _userManager = userManager;
        _context = context;
        _burndownModel = new BurndownModel();
    }

    public IActionResult Burndown(int projectId)
    {
        if (User.Identity == null || User.Identity.IsAuthenticated == false)
        {
            return RedirectToAction("Login", "Account");
        }

        if (_burndownModel.ValidUserClaim(_context, _userManager, User, projectId) == false)
        {
            ViewBag.DeniedAccess = true;
            return View();
        }

        ViewBag.DeniedAccess = false;
        ViewBag.projectId = projectId;

        return View(_burndownModel);
    }

    [HttpPost]
    public List<DailyTicketCounts> GetDailyTicketCounts(int projectId)
    {
        List<DailyTicketCounts> data = _burndownModel.GetBurndownData(_context, projectId);
        _logger.LogInformation("DATA in BurndownController: " + JsonConvert.SerializeObject(data));

        return data;
    }
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using CodeBuggy.Data;
using CodeBuggy.Models;
using System.Diagnostics;
using CodeBuggy.Models.Projects;
using CodeBuggy.Helpers;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;
using System.Net.Sockets;
namespace CodeBuggy.Controllers;

public class ProjectsController : Controller
{
    private readonly ILogger<ProjectsController> _logger;
    private readonly ProjectsListModel _projectsListModel;
    private readonly ProjectBoardModel _projectBoardModel;
    private readonly NotificationModel _notificationModel;
    private readonly AppDbContext _context;
    public ProjectsController(ILogger<ProjectsController> logger, AppDbContext context, UserManager<AppUser> userManager)
    {
        _logger = logger;
        _projectsListModel = new ProjectsListModel(_logger, context, userManager);
        _projectBoardModel = new ProjectBoardModel(_logger, context, userManager);
        _notificationModel = new NotificationModel();
        _context = context;
    }

    // ******************************************************************************* //
    // ******************************** Project List ********************************* // 
    // ******************************************************************************* //
    public IActionResult ProjectsList(int page = 1)
    {
        var projectList = _projectsListModel.GetProjectsList(page, User);

        if (projectList != null)
        {
            ViewBag.ProjectTable = HtmlHelpers.RenderProjectTable(projectList, Url);
            ViewBag.Pagination = HtmlHelpers.RenderPagination(projectList, i => Url.Action("ProjectsList", new { page = i }));
        }

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddExistingProject(ProjectsListModel.InputModel input)
    {
        if (string.IsNullOrWhiteSpace(input.Name) || string.IsNullOrWhiteSpace(input.AccessCode))
        {
            return Json(new { success = false, message = "Project Name and Access Code must be provided" });
        }

        OperationResult result = await _projectsListModel.AddExistingProject(input, User);

        return Json(new { success = result.Success, message = result.Message });
    }

    [HttpPost]
    public async Task<IActionResult> AddNewProject(ProjectsListModel.InputModel input)
    {
        if (string.IsNullOrWhiteSpace(input.Name))
        {
            return Json(new { success = false, message = "Project Name must be provided" });
        }

        if (input.Name.Length > 20)
        {
            return Json(new { success = false, message = "Project Name must not exceed 20 characters" });
        }

        if (input.Name.Contains(' '))
        {
            return Json(new { success = false, message = "Project Name must not contain white spaces" });
        }

        OperationResult result = await _projectsListModel.AddNewProjectAsync(input, User);

        return Json(new { success = result.Success, message = result.Message });
    }

    [HttpPost]
    public async Task<IActionResult> DeleteProject(ProjectsListModel.InputModel input)
    {
        if (string.IsNullOrWhiteSpace(input.AccessCode))
        {
            return Json(new { success = false, message = "Project Access Code must be provided" });
        }

        OperationResult result = await _projectsListModel.DeleteProjectAsync(input.AccessCode, User);

        return Json(new { success = result.Success, message = result.Message });
    }

    [HttpPost]
    public IActionResult InviteEmail(ProjectsListModel.InputModel input)
    {
        if (string.IsNullOrWhiteSpace(input.Email))
        {
            return Json(new { success = false, message = "User could not be invited" });
        }

        OperationResult result = _projectsListModel.InviteEmail(input, User);

        return Json(new { success = result.Success, message = result.Message });
    }

    // ******************************************************************************* //
    // ******************************** Project Board ******************************** // 
    // ******************************************************************************* //

    [AcceptVerbs("GET", "POST")]
    public IActionResult ProjectBoard(int projectId, string ticket, bool userFilter)
    {
        Console.WriteLine("Chris projectId: " + projectId + " Ticket: " + ticket + " userFilter: " + userFilter);
        if (User.Identity == null || User.Identity.IsAuthenticated == false)
        {
            return RedirectToAction("Login", "Account");
        }

        if (_projectBoardModel != null && _projectBoardModel.ValidUserClaim(User, projectId))
        {
            bool result = _projectBoardModel.PopulateTickets(projectId, User, userFilter);
            if (result == false)
            {
                ViewBag.DeniedAccess = true;
                return View();
            }

            ViewBag.ProjectTitle = _projectBoardModel?.GetProjectName(projectId);
            ViewBag.DeniedAccess = false;
            ViewBag.ProjectId = projectId;
            ViewBag.Username = _projectBoardModel?.GetUsername(User);
            ViewBag.UserFilter = userFilter;

            if (ticket != null)
            {
                ViewBag.TicketId = ticket;
            }
            else
            {
                ViewBag.TicketId = null;
            }

            return View(_projectBoardModel);
        }

        ViewBag.DeniedAccess = true;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddTicket(ProjectBoardModel.InputModel input, int projectId)
    {
        OperationResult result = await _projectBoardModel.AddTicketToProject(User, input, projectId);

        return Json(new { success = result.Success, message = result.Message });
    }

    [HttpPost]
    public async Task<IActionResult> ChangeTicketStatus(int projectId, int ticketId, string status)
    {
        if (User.Identity == null || User.Identity.IsAuthenticated == false)
        {
            return RedirectToAction("Login", "Account");
        }

        OperationResult result = await _projectBoardModel.ChangeTicketStatus(User, projectId, ticketId, status);

        return Json(new { success = result.Success, message = result.Message });
    }

    [HttpPost]
    public async Task<IActionResult> SaveTicketChanges(int projectId, int ticketId, ProjectBoardModel.InputModel input)
    {

        if (User.Identity == null || User.Identity.IsAuthenticated == false)
        {
            return RedirectToAction("Login", "Account");
        }

        OperationResult result = await _projectBoardModel.SaveTicketChanges(User, projectId, ticketId, input);

        return Json(new { success = result.Success, message = result.Message });
    }

    [HttpPost]
    public async Task<IActionResult> GetTicketStatus(int projectId, int ticketId)
    {
        if (User.Identity == null || User.Identity.IsAuthenticated == false)
        {
            return RedirectToAction("Login", "Account");
        }

        int ticketStatusInt = await _projectBoardModel.GetTicketStatus(User, projectId, ticketId);

        if (ticketStatusInt != -1)
        {
            return Json(new { success = true, ticketStatus = ticketStatusInt });
        }

        return Json(new { success = true, ticketStatus = ticketStatusInt });
    }

    [HttpPost]
    public async Task<IActionResult> DeleteTicket(int projectId, int ticketId)
    {
        if (User.Identity == null || User.Identity.IsAuthenticated == false)
        {
            return RedirectToAction("Login", "Account");
        }

        OperationResult result = await _projectBoardModel.DeleteTicket(User, projectId, ticketId);

        return Json(new { success = result.Success, message = result.Message });
    }


    [HttpPost]
    public List<Notification> GetNotifications(int projectId)
    {
        List<Notification> data = _notificationModel.GetNotificationData(_context, projectId);

        return data;
    }


    [HttpPost]
    public async Task<IActionResult> AddCommentToTicket(int projectId, int ticketId, string comment)
    {
        if (User.Identity == null || User.Identity.IsAuthenticated == false)
        {
            return RedirectToAction("Login", "Account");
        }

        OperationResult result = await _projectBoardModel.AddCommentToTicket(User, projectId, ticketId, comment);

        return Json(new { success = result.Success, message = result.Message });
    }

    [HttpPost]
    public IActionResult GetComments(int projectId, int ticketId)
    {
        if (User.Identity == null || User.Identity.IsAuthenticated == false)
        {
            return RedirectToAction("Login", "Account");
        }

        var comments = new List<Comment>();

        OperationResult result = _projectBoardModel.GetComments(User, projectId, ticketId, ref comments);

        return Json(new { success = result.Success, message = result.Message, commentsData = comments });
    }

    [HttpPost]
    public async Task<IActionResult> GetTicketInfo(int projectId, int searchTicketId)
    {
        if (User.Identity == null || User.Identity.IsAuthenticated == false)
        {
            return RedirectToAction("Login", "Account");
        }

        var foundTicket = await _projectBoardModel?.GetTicketInfo(User, projectId, searchTicketId);

        if (foundTicket != null)
        {
            var assigneeUser = "false";
            var username = _projectBoardModel?.GetUsername(User);
            if (username != null && username == foundTicket.Assignee)
            {
                assigneeUser = "true";
            }
            return Json(new { success = true, ticketJson = JsonConvert.SerializeObject(foundTicket), assignedToUser = assigneeUser.ToLower() });
        }

        return Json(new { success = false, message = "Ticket not found" }); ;
    }

    [HttpPost]

Views/Projects/ProjectBoard.cshtml
@using CodeBuggy.Controllers
@using CodeBuggy.Data
@using CodeBuggy.Helpers
@using CodeBuggy.Models.Projects
@using System.Text.Json
@using System.Web.Helpers
@using Microsoft.AspNetCore.Html
@using Newtonsoft.Json

<script type="text/javascript" src="~/js/projectBoard.js"></script>
<style>
    .container {
        max-width: fit-content !important;
        display: flex !important;
        align-items: center !important;
    }
</style>
@model ProjectBoardModel

@{
    Func<IHtmlContent> RenderProjectTicketStatusDropdownList = () =>
    {
        var enumValues = Enum.GetValues(typeof(TicketStatus)).Cast<TicketStatus>();
        var options = enumValues.Select(e => $"<option value='{e}'>{e}</option>");
        var dropdownHtml = $@"
<select id='statusSelect' name='Input.TicketStatusValue' class='form-control'>
{string.Join("", options)}
</select>";
        return new HtmlString(dropdownHtml);
    };

    Func<IHtmlContent> RenderProjectTicketPriorityDropdownList = () =>
    {
        var enumValues = Enum.GetValues(typeof(TicketPriority)).Cast<TicketPriority>();
        var options = enumValues.Select(e => $"<option value='{e}'>{e}</option>");
        var dropdownHtml = $@"
            <select id='prioritySelect' name='Input.TicketPriorityValue' class='form-control'>
            {string.Join("", options)}
            </select>";
        return new HtmlString(dropdownHtml);
    };
}
@if (ViewBag.DeniedAccess == false)
{
    <div style="display: flex; justify-content: space-between; align-items: center;">
    <div id="searchContainer" style="position: relative;">
        <form id="searchForm">
            <input type="text" id="searchInput" placeholder="Search by Title, Description, or ID" autocomplete="off">
            <input type="hidden" id="projectId" value="@ViewBag.ProjectId" />
        </form>
        <div id="searchResultsDropdown"></div>
    </div>
    <h2 style="text-align: center; flex: 1;">@ViewBag.ProjectTitle</h2>
    @{
        var bg_color = "";
        if (ViewBag.UserFilter == true)
        {
            bg_color = "background: #1861ac;";
        }
    }
    <a class="create-button" id="toggleUserTickets" style="text-align: right; margin-right: 10px; @bg_color" onclick="toggleUserTickets()">
        <span class="material-symbols-outlined">
            person_search
        </span>
    </a>
    <a class="create-button" id="toggleBacklogButton" style="text-align: right; margin-right: 10px;" onclick="toggleBackLog()">
        <span class="material-symbols-outlined">
            stacks
        </span>
    </a>
    <a class="create-button" style="text-align: right; margin-right: 10px;"
        onclick="fetchAndDisplayNotifications(@ViewBag.ProjectId)">
            <span class="material-symbols-outlined">notifications</span>
    </a>
    <a class="create-button" style="text-align: left; margin-right: 10px;" asp-controller="Burndown"
        asp-action="Burndown" asp-route-projectId="@ViewBag.ProjectId">
        <span class="material-symbols-outlined" style="margin-right: 5px;">
            query_stats
        </span>
    </a>
    <a class="create-button" style="text-align: right;" onclick="showPopup('addTicketPopup')">
        <span class="material-symbols-outlined">
            add
        </span>
    </a>
</div>

    <div class="board-container">
    <div class="board">
        <div class="column" id="backlogColumn" style="display: none;" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h3 class="column-title">Backlog</h3>
            <div class="tickets-container">
                @Html.RenderTickets(Model.Tickets, TicketStatus.Backlog, (string)@ViewBag.Username)
            </div>
        </div>
        <div class="column" id="todoColumn" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h3 class="column-title">To Do</h3>
            <div class="tickets-container">
                @Html.RenderTickets(Model.Tickets, TicketStatus.ToDo, (string)@ViewBag.Username)
            </div>
        </div>
        <div class="column" id="inProgressColumn" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h3 class="column-title">In Progress</h3>
            <div class="tickets-container">
                @Html.RenderTickets(Model.Tickets, TicketStatus.InProgress, (string)@ViewBag.Username)
            </div>
        </div>
        <div class="column" id="reviewColumn" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h3 class="column-title">Review</h3>
            <div class="tickets-container">
                @Html.RenderTickets(Model.Tickets, TicketStatus.Review, (string)@ViewBag.Username)
            </div>
        </div>
        <div class="column" id="doneColumn" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h3 class="column-title">Done</h3>
            <div class="tickets-container">
                @Html.RenderTickets(Model.Tickets, TicketStatus.Done, (string)@ViewBag.Username)
            </div>
        </div>
        <div id="errorTooltip"></div>
    </div>
    </div>

@****************************************************************@
@************************* Dynamic Code *************************@
@****************************************************************@

    string addTicketForm = $@"
<form id='addTicketForm' action='AddTicket' method='post' style='text-align: left;'>";

    string editTicketForm = $@"
<form id='editTicketForm' action='SaveTicketChanges' method='post' style='text-align: left;'>";

    string ticketId = $@"<input type='hidden' name='ticketId' id='changeTicketId' style='display: none'></input>";

    string upperContainer = $@"<div id='upperContainer'>";

    string assignmentContainer = $@"
<div id='assignmentContainer'>
<div id='assigneeContainer'>
<div id='assigneeLabel'>Assigned To</div>
<div id='assigneeName'></div>
</div>
<div style='display: flex; justify-content: flex-end;'>
<button id='assignToMeButton'>Assign me</button>
</div>
<div id='reporterContainer'>
<div id='reporterLabel'>Reporter</div>
<div id='reporterName'></div>
</div>
</div>";

    string ticketDetailsContainer = $@"<div id='ticketDetailsContainer' style='float: left;'>";
    string ticketStatusesContainer = $@"<div id='ticketStatusesContainer'>";

    string ticketTitleInput = @"
<div id='ticketTitleInput' class='form-floating mb-3' style='max-width: 605px'>
<input name='Input.TicketTitle' class='form-control' autocomplete='TicketTitle' aria-required='true'
placeholder=''/>
<label name='Input.TicketTitle'>Title</label>
</div>";

    string ticketPriorityDropdown = $@"
<div id='ticketPriority' class='form-floating mb-3 position-relative' style='max-width: 300px; display:
inline-block;width: -webkit-fill-available;'>
{RenderProjectTicketPriorityDropdownList()}
<label name='Input.TicketPriorityValue'>Priority</label>
<div class='dropdown-arrow'>▼</div>
</div>";

    string ticketStatusDropdown = $@"
<div id='ticketStatus' class='form-floating mb-3 position-relative' style='max-width: 300px; display:
inline-block;width: -webkit-fill-available;'>
{RenderProjectTicketStatusDropdownList()}
<label name='Input.TicketStatusValue'>Status</label>
<div class='dropdown-arrow'>▼</div>
</div>";

    string ticketDescriptionInput = @"
<div id='ticketDescriptionInput' class='form-floating mb-3'>
<input name='Input.TicketDescription' type='hidden'>
</div>
<input type='hidden' id='ticketDescription' name='Input.TicketDescription'>";

    string projectIdDOM = $@"<input type='hidden' name='projectId' value='{@ViewBag.ProjectId}' />";

    string formButtons = @"
<div style='display: flex; flex-wrap: wrap; justify-content: center;'>
";

    string submitButton = @"
<button id='submitButton' type='submit' class='button-general btn-primary mb-3 mt-5'
style='margin-right: 20px; text-align: center; max-width: 200px'>
";

    string deleteButton = @"
<button id='deleteButton' type='button' class='button-general btn-danger mb-3 mt-5'
style='text-align: center; max-width: 160px'>
";

    string confirmTicketDelete = $@"
<div style='display: flex; flex-wrap: wrap; justify-content: center;'>
<input type='hidden' name='projectId' value='{@ViewBag.ProjectId}' />
<input type='hidden' name='ticketId'></input>
<button id='confirmDeleteButton' type='button' class='button-general btn-danger mb-3 mt-5'
style='margin-right: 20px; text-align: center; max-width: 160px'>Confirm</button>
<button id='cancelDeleteButton' type='button' class='button-general btn-primary mb-3 mt-5'
style='text-align: center; max-width: 200px'>Cancel</button>
</div>
";

    string addCommentDom = $@"
<div id='addCommentBox' class='comment-box' style='max-width: 900px;'>
<h3>Comments</h3>
<div id='addCommentTextBox' class='form-floating mb-3'></div>
<button id='addCommentButton' class='button-general' style='font-size: 15px;'>Add Comment</button>
<div id='buttonsContainer' style='display: none; flex-wrap: wrap; justify-content: left'>
<button id='saveCommentButton' class='button-general btn-primary mb-3 mt-5' style='width: 80px; height: 40px; padding:
0px; margin: 2px !important;'>Save</button>
<button id='cancelCommentButton' class='button-general btn-danger mb-3 mt-5' style='width: 80px; height: 40px; padding:
0px; margin: 2px !important;'>Cancel</button>
</div>
<input name='commentInput' type='hidden'></input>
</div>";

    string existingComments = $@"<div id='existingCommentsBox' class='comment-box' style='max-width: 900px'></div>";

    var addTicketFormDOM = addTicketForm + ticketTitleInput + @Html.Raw(ticketPriorityDropdown) +
    @Html.Raw(ticketStatusDropdown) + ticketDescriptionInput + projectIdDOM + submitButton + "Create Ticket</button>" +
    "</form>";
    var addTicketPopup = new Popup();
    var addTicketPopupHTML = addTicketPopup.CreatePopup("addTicketPopup", "Add Ticket", new string[] { addTicketFormDOM });
    @Html.Raw(addTicketPopupHTML)

    var upperDOM = upperContainer + ticketDetailsContainer + ticketTitleInput + ticketStatusesContainer +
    @Html.Raw(ticketPriorityDropdown) + @Html.Raw(ticketStatusDropdown) + "</div></div>" + assignmentContainer + "</div>";
    var editTicketDOM = editTicketForm + ticketId + upperDOM + ticketDescriptionInput + projectIdDOM + formButtons +
    submitButton + "Save Changes</button>" + deleteButton + "Delete Ticket</button></div>" + addCommentDom +
    existingComments + "</form>";
    var editTicketPopup = new Popup();
    var editTicketPopupHTML = editTicketPopup.CreatePopup("editTicketPopup", "", new string[] { editTicketDOM });
    @Html.Raw(editTicketPopupHTML)

    var deleteTicketConfirmDOM = confirmTicketDelete;
    var deleteTicketConfirmPopup = new Popup();
    var deleteTicketConfirmHTML = deleteTicketConfirmPopup.CreatePopup("confirmDeletePopup", "", new string[] {
confirmTicketDelete });
    @Html.Raw(deleteTicketConfirmHTML)

    if (ViewBag.TicketId != null)
    {
        var ticketDetailsPopup = @Html.GetTicketInfo(Model.Tickets, (string)ViewBag.TicketId, (string)@ViewBag.Username);
        if (ticketDetailsPopup != null)
        {
            <script>
                var ticketJson = JSON.parse(@Html.Raw(JsonConvert.SerializeObject(ticketDetailsPopup.TicketJson)));
                showTicket(ticketJson, '@ticketDetailsPopup.AssignedToUser');
            </script>
        }
        else
        {
            <script>
                var currentURL = new URL(window.location.href);
                if (currentURL.searchParams.has('ticket')) {
                    currentURL.searchParams.delete('ticket');
                    history.pushState({}, '', currentURL.href);
                }
            </script>
        }
    }
}
else
{
    <div>Access Denied: This page does not exist</div>
}